"""
Create Supabase tables used to capture thematic and statistical factor matches.

Run this script after providing a Postgres connection string (e.g. noqa:
`SUPABASE_DB_URL` or `DATABASE_URL`) that points at the Supabase project.
"""

import os
from textwrap import dedent

import psycopg2
from dotenv import load_dotenv
from supabase import Client, create_client


load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
supabase: Client | None = None

if SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
    try:
        supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
    except Exception as exc:
        print(f"Warning: could not initialize Supabase client: {exc}")
        print("Note: Service role key is required for database operations.")
else:
    if not SUPABASE_URL:
        print("Warning: SUPABASE_URL not set. Supabase features will be disabled.")
    if not SUPABASE_SERVICE_ROLE_KEY:
        print("Warning: SUPABASE_SERVICE_ROLE_KEY not set. Supabase features will be disabled.")
        print("Note: Service role key is required for write operations. Anon key will not work.")


SQL_STATEMENTS = (
    dedent(
        """\
        CREATE TABLE IF NOT EXISTS factor_results_thematic (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_date DATE DEFAULT CURRENT_DATE,
            factor_id BIGINT REFERENCES factors(id),
            ticker TEXT,
            confidence_score FLOAT,
            reasoning TEXT
        );
        """
    ),
    dedent(
        """\
        CREATE TABLE IF NOT EXISTS factor_results_statistical (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_date DATE DEFAULT CURRENT_DATE,
            factor_id BIGINT REFERENCES factors(id),
            ticker TEXT,
            metric_value FLOAT,
            percentile_rank FLOAT
        );
        """
    ),
    dedent(
        """\
        CREATE TABLE IF NOT EXISTS stock_prices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ticker TEXT NOT NULL,
            date DATE NOT NULL,
            open FLOAT,
            high FLOAT,
            low FLOAT,
            close FLOAT,
            volume BIGINT,
            adjusted_close FLOAT,
            UNIQUE (ticker, date)
        );
        """
    ),
    "CREATE INDEX IF NOT EXISTS idx_stock_prices_ticker_date ON stock_prices (ticker, date DESC);",
    dedent(
        """\
        CREATE TABLE IF NOT EXISTS factor_performance (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            factor_id BIGINT REFERENCES factors(id),
            run_date DATE NOT NULL DEFAULT CURRENT_DATE,
            num_holdings INT,
            perf_1d FLOAT,
            perf_5d FLOAT,
            perf_1m FLOAT,
            perf_3m FLOAT,
            perf_6m FLOAT,
            perf_1y FLOAT,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE (factor_id, run_date)
        );
        """
    ),
    "CREATE INDEX IF NOT EXISTS idx_factor_performance_date ON factor_performance (run_date DESC);",
    "CREATE INDEX IF NOT EXISTS idx_factor_performance_factor ON factor_performance (factor_id);",
    dedent(
        """\
        CREATE TABLE IF NOT EXISTS factor_zscore_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            factor_id BIGINT REFERENCES factors(id),
            date DATE NOT NULL,
            zscore FLOAT,
            factor_value FLOAT,
            UNIQUE (factor_id, date)
        );
        """
    ),
    "CREATE INDEX IF NOT EXISTS idx_zscore_factor_date ON factor_zscore_history (factor_id, date DESC);",
)


def create_tables(connection: psycopg2.extensions.connection) -> None:
    """Execute the required DDL to ensure the new tables exist."""
    with connection.cursor() as cursor:
        for statement in SQL_STATEMENTS:
            cursor.execute(statement)


def main() -> None:
    """Connect to Supabase and run the schema migration."""
    database_url = os.getenv("SUPABASE_DB_URL") 
    print(database_url)
    if not database_url:
        raise RuntimeError(
            "Missing database connection string. Set SUPABASE_URL or DATABASE_URL in your .env file."
        )

    print("🌱 Ensuring match result tables exist in Supabase...")
    try:
        with psycopg2.connect(database_url) as connection:
            connection.autocommit = True
            create_tables(connection)
    except Exception as exc:
        print(f"❌ Failed to create tables: {exc}")
        raise
    else:
        print("✅ Tables created/updated successfully.")


if __name__ == "__main__":
    main()

